name: GitHub Unit Testing
run-name: ${{ github.actor }} first test baby wooooo
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Checkout latest code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        working-directory: unittesting
        env:
          CI: true
        run: |
          npm install
          npm run test


