name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: Checkout latest code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit packages
        working-directory: insecure
        run: npm audit --audit-level moderate
        env:
          CI: true
